# -*- coding: utf-8 -*-
"""pdf rag

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FEkKTf0iMzZoabw5GeyKcBdqwrvm5n9d
"""

# Cell 1: Check GPU (Runtime → Change runtime type → T4 GPU)
!nvidia-smi

# Cell 2: Install required packages
!pip install -q pypdf2 langchain langchain-community faiss-cpu sentence-transformers streamlit pyngrok google-generativeai streamlit-chat
!pip install -q nltk rank-bm25 tiktoken

# Cell 3: Complete RAG Chatbot Code
import os
import re
import pickle
from typing import List, Tuple, Dict
import nltk
from nltk.tokenize import sent_tokenize

# Download NLTK data
nltk.download('punkt', quiet=True)
nltk.download('punkt_tab', quiet=True)

# Import libraries
import PyPDF2
from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
from google.colab import files
import warnings
warnings.filterwarnings('ignore')

class PDFRAGChatbot:
    """Complete RAG Chatbot with Hybrid Search & Source Citations"""

    def __init__(self):
        # Initialize embedding model (BGE-small is top performer on MTEB)
        self.embedding_model = SentenceTransformer('BAAI/bge-small-en-v1.5')
        self.embedding_dim = 384

        # Initialize FAISS index
        self.index = faiss.IndexFlatL2(self.embedding_dim)

        # Storage for chunks and metadata
        self.chunks = []  # Store text chunks
        self.metadata = []  # Store (filename, page_num)

        # BM25 for keyword search
        self.bm25 = None
        self.tokenized_chunks = []

        print("✅ RAG Chatbot initialized!")
        print(f"📊 Embedding dimension: {self.embedding_dim}")

    def extract_text_from_pdf(self, pdf_file, filename: str) -> List[Tuple[str, int]]:
        """Extract text from PDF with page numbers"""
        pdf_reader = PyPDF2.PdfReader(pdf_file)
        pages_content = []

        for page_num, page in enumerate(pdf_reader.pages, start=1):
            text = page.extract_text()
            if text.strip():
                pages_content.append((text, page_num, filename))

        print(f"📄 Extracted {len(pages_content)} pages from {filename}")
        return pages_content

    def semantic_chunking(self, text: str, chunk_size: int = 500, overlap: int = 100) -> List[str]:
        """Intelligent chunking respecting sentence boundaries"""
        sentences = sent_tokenize(text)
        chunks = []
        current_chunk = []
        current_length = 0

        for sentence in sentences:
            sentence_len = len(sentence.split())

            if current_length + sentence_len <= chunk_size:
                current_chunk.append(sentence)
                current_length += sentence_len
            else:
                if current_chunk:
                    chunks.append(' '.join(current_chunk))
                # Start new chunk with overlap
                overlap_idx = max(0, len(current_chunk) - overlap // 20)
                current_chunk = current_chunk[overlap_idx:] + [sentence]
                current_length = sum(len(s.split()) for s in current_chunk)

        if current_chunk:
            chunks.append(' '.join(current_chunk))

        return chunks

    def process_documents(self, uploaded_files) -> int:
        """Process multiple PDFs: extract, chunk, embed, and index"""
        all_text_chunks = []
        all_metadata = []

        for uploaded_file in uploaded_files:
            filename = uploaded_file.name
            print(f"\n📚 Processing: {filename}")

            # Extract text with page numbers
            pages_content = self.extract_text_from_pdf(uploaded_file, filename)

            # Chunk each page
            for text, page_num, fname in pages_content:
                chunks = self.semantic_chunking(text)
                for chunk in chunks:
                    all_text_chunks.append(chunk)
                    all_metadata.append({
                        'filename': fname,
                        'page': page_num,
                        'chunk_preview': chunk[:100] + "..."
                    })

        # Store chunks and metadata
        self.chunks = all_text_chunks
        self.metadata = all_metadata

        # Generate embeddings and build FAISS index
        print(f"\n🔢 Generating embeddings for {len(self.chunks)} chunks...")
        embeddings = self.embedding_model.encode(self.chunks, show_progress_bar=True)
        self.index.add(np.array(embeddings).astype('float32'))

        # Prepare for BM25
        self.tokenized_chunks = [chunk.lower().split() for chunk in self.chunks]
        self._build_bm25()

        print(f"\n✅ Indexed {len(self.chunks)} chunks from {len(uploaded_files)} files")
        return len(self.chunks)

    def _build_bm25(self):
        """Build BM25 index for keyword search"""
        from rank_bm25 import BM25Okapi
        self.bm25 = BM25Okapi(self.tokenized_chunks)

    def hybrid_search(self, query: str, top_k: int = 5, alpha: float = 0.7) -> List[Tuple[int, float]]:
        """
        Hybrid search combining semantic (FAISS) and keyword (BM25)
        alpha: weight for semantic search (0.7 = 70% semantic, 30% keyword)
        """
        # Semantic search
        query_embedding = self.embedding_model.encode([query])
        distances, semantic_indices = self.index.search(np.array(query_embedding).astype('float32'), top_k * 2)

        # Keyword search (BM25)
        tokenized_query = query.lower().split()
        bm25_scores = self.bm25.get_scores(tokenized_query)
        keyword_indices = np.argsort(bm25_scores)[::-1][:top_k * 2]

        # Combine scores
        combined_scores = {}
        for rank, idx in enumerate(semantic_indices[0]):
            semantic_score = 1.0 / (rank + 1)  # Reciprocal rank
            combined_scores[idx] = alpha * semantic_score

        for rank, idx in enumerate(keyword_indices):
            keyword_score = bm25_scores[idx] / (bm25_scores[keyword_indices[0]] + 1e-8)
            combined_scores[idx] = combined_scores.get(idx, 0) + (1 - alpha) * keyword_score

        # Sort by combined score
        sorted_indices = sorted(combined_scores.keys(), key=lambda x: combined_scores[x], reverse=True)[:top_k]
        return [(idx, combined_scores[idx]) for idx in sorted_indices]

    def search(self, query: str, top_k: int = 5) -> List[Dict]:
        """Search for relevant chunks with metadata"""
        if not self.chunks:
            return []

        # Use hybrid search
        results = self.hybrid_search(query, top_k)

        formatted_results = []
        for idx, score in results:
            formatted_results.append({
                'text': self.chunks[idx],
                'metadata': self.metadata[idx],
                'score': score
            })

        return formatted_results

    def generate_answer(self, query: str, retrieved_chunks: List[Dict]) -> Dict:
        """Generate answer using LLM (Gemini or local alternative)"""
        # Build context from retrieved chunks
        context = []
        citations = []

        for chunk in retrieved_chunks:
            context.append(chunk['text'])
            citations.append(f"📄 {chunk['metadata']['filename']} (Page {chunk['metadata']['page']})")

        context_text = "\n\n---\n\n".join(context)

        # Prompt engineering for zero hallucination
        prompt = f"""You are a precise AI assistant for legal document analysis.
Answer the question STRICTLY based on the provided context.
If the answer cannot be found in the context, say "I cannot answer that based on the provided documents."

CONTEXT:
{context_text}

QUESTION: {query}

ANSWER (with citations):"""

        # Use Gemini (free tier)
        import google.generativeai as genai

        # Get API key from user (run this once)
        if 'GEMINI_API_KEY' not in os.environ:
            print("\n⚠️ Please enter your Gemini API key (free from makersuite.google.com/app/apikey)")
            api_key = input("Enter API key: ")
            os.environ['GEMINI_API_KEY'] = api_key

        genai.configure(api_key=os.environ['GEMINI_API_KEY'])
        model = genai.GenerativeModel('gemini-1.5-flash')

        response = model.generate_content(prompt)

        return {
            'answer': response.text,
            'citations': citations,
            'retrieved_chunks': len(retrieved_chunks)
        }

    def query(self, question: str) -> Dict:
        """Full pipeline: search + generate"""
        # Step 1: Retrieve relevant chunks
        relevant_chunks = self.search(question)

        if not relevant_chunks:
            return {
                'answer': "No documents have been uploaded yet. Please upload PDF files first.",
                'citations': [],
                'retrieved_chunks': 0
            }

        # Step 2: Generate answer
        result = self.generate_answer(question, relevant_chunks)
        return result

# Initialize the chatbot
chatbot = PDFRAGChatbot()
print("🎉 Chatbot ready! Use the functions below to upload PDFs and ask questions.")

# Cell 4: Upload PDFs and ask questions
from google.colab import files
import ipywidgets as widgets
from IPython.display import display, Markdown, clear_output

# Upload PDFs
print("📁 Upload your PDF files:")
uploaded_files = list(files.upload().keys())

# Create file objects for processing
import io
file_objects = []
for filename in uploaded_files:
    with open(filename, 'rb') as f:
        # Create a mock file object
        class MockFile:
            def __init__(self, name, data):
                self.name = name
                self.data = data
            def read(self):
                return self.data
        file_objects.append(MockFile(filename, f.read()))

# Process documents
if file_objects:
    num_chunks = chatbot.process_documents(file_objects)
    print(f"\n✅ Processing complete! {num_chunks} text chunks indexed.")
else:
    print("No files uploaded.")

# Interactive Q&A
print("\n" + "="*50)
print("🤖 Ask questions about your PDFs")
print("="*50)

while True:
    question = input("\n❓ Your question (or type 'quit' to exit): ")

    if question.lower() in ['quit', 'exit', 'q']:
        print("👋 Goodbye!")
        break

    if not question.strip():
        continue

    print("\n🔍 Searching and generating answer...")
    result = chatbot.query(question)

    print("\n" + "="*50)
    print("💡 ANSWER:")
    print("="*50)
    print(result['answer'])

    if result['citations']:
        print("\n📚 SOURCES:")
        for citation in set(result['citations']):  # Remove duplicates
            print(f"  {citation}")

    print("\n" + "-"*50)

!pip install -q pypdf2 sentence-transformers faiss-cpu nltk rank-bm25 google-generativeai

import os
import io
import numpy as np
import nltk
from nltk.tokenize import sent_tokenize
import PyPDF2
from sentence_transformers import SentenceTransformer
import faiss
from rank_bm25 import BM25Okapi
import google.generativeai as genai
from google.colab import files
import warnings
warnings.filterwarnings('ignore')

# Download NLTK data
nltk.download('punkt', quiet=True)

class SimpleRAGChatbot:
    """RAG Chatbot - Fixed file handling for Colab"""

    def __init__(self):
        print("📚 Initializing RAG Chatbot...")
        # Using MiniLM - works great on CPU
        self.embedding_model = SentenceTransformer('all-MiniLM-L6-v2')
        self.embedding_dim = 384

        # FAISS index for similarity search
        self.index = faiss.IndexFlatL2(self.embedding_dim)

        # Storage
        self.chunks = []
        self.metadata = []
        self.tokenized_chunks = []
        self.bm25 = None

        print(f"✅ Ready! Embedding dimension: {self.embedding_dim}")

    def extract_pdf_text(self, file_path, filename):
        """Extract text from PDF file path"""
        try:
            with open(file_path, 'rb') as f:
                pdf_reader = PyPDF2.PdfReader(f)
                pages = []

                for page_num, page in enumerate(pdf_reader.pages, 1):
                    text = page.extract_text()
                    if text and text.strip():
                        pages.append((text.strip(), page_num, filename))

                return pages
        except Exception as e:
            print(f"  ⚠️ Error reading {filename}: {str(e)[:50]}")
            return []

    def smart_chunking(self, text, chunk_size=400):
        """Split text into chunks respecting sentences"""
        sentences = sent_tokenize(text)
        chunks = []
        current_chunk = []
        current_len = 0

        for sentence in sentences:
            word_count = len(sentence.split())

            if current_len + word_count <= chunk_size:
                current_chunk.append(sentence)
                current_len += word_count
            else:
                if current_chunk:
                    chunks.append(' '.join(current_chunk))
                current_chunk = [sentence]
                current_len = word_count

        if current_chunk:
            chunks.append(' '.join(current_chunk))

        return chunks

    def add_documents(self, file_paths):
        """Process PDF files from file paths"""
        all_chunks = []
        all_metadata = []

        for file_path in file_paths:
            filename = os.path.basename(file_path)
            print(f"\n📄 Processing: {filename}")

            # Extract text
            pages = self.extract_pdf_text(file_path, filename)

            if not pages:
                print(f"  ⚠️ No text extracted. PDF might be scanned or empty.")
                continue

            for text, page_num, fname in pages:
                chunks = self.smart_chunking(text)
                for chunk in chunks:
                    all_chunks.append(chunk)
                    all_metadata.append({
                        'filename': fname,
                        'page': page_num,
                        'preview': chunk[:100] + "..."
                    })

            print(f"  ✓ Extracted {len(pages)} pages, {len(chunks)} chunks")

        # Store
        self.chunks = all_chunks
        self.metadata = all_metadata

        if not self.chunks:
            print("\n⚠️ No text extracted. Make sure PDFs have selectable text (not scanned images).")
            return 0

        # Generate embeddings (works fine on CPU)
        print(f"\n🔢 Generating embeddings for {len(self.chunks)} chunks...")
        embeddings = self.embedding_model.encode(self.chunks, show_progress_bar=True)

        # Add to FAISS
        self.index.add(np.array(embeddings).astype('float32'))

        # Setup BM25 for keyword search
        self.tokenized_chunks = [chunk.lower().split() for chunk in self.chunks]
        self.bm25 = BM25Okapi(self.tokenized_chunks)

        print(f"\n✅ Success! Indexed {len(self.chunks)} chunks from {len(file_paths)} files")
        return len(self.chunks)

    def search(self, query, top_k=4):
        """Hybrid search: semantic + keyword"""
        if not self.chunks:
            return []

        # Semantic search with FAISS
        query_embedding = self.embedding_model.encode([query])
        distances, semantic_idx = self.index.search(
            np.array(query_embedding).astype('float32'),
            top_k * 2
        )

        # Keyword search with BM25
        tokenized_query = query.lower().split()
        bm25_scores = self.bm25.get_scores(tokenized_query)
        keyword_idx = np.argsort(bm25_scores)[::-1][:top_k * 2]

        # Simple score combination
        scores = {}
        for rank, idx in enumerate(semantic_idx[0]):
            scores[idx] = 1.0 / (rank + 1)
        for rank, idx in enumerate(keyword_idx):
            scores[idx] = scores.get(idx, 0) + 1.0 / (rank + 1)

        # Get top results
        top_indices = sorted(scores.keys(), key=lambda x: scores[x], reverse=True)[:top_k]

        results = []
        for idx in top_indices:
            results.append({
                'text': self.chunks[idx],
                'metadata': self.metadata[idx],
                'score': scores[idx]
            })

        return results

    def ask(self, question, api_key):
        """Ask a question and get answer with citations"""
        # Search for relevant content
        relevant_chunks = self.search(question)

        if not relevant_chunks:
            return {
                'answer': "Please upload PDF documents first using the upload button above.",
                'citations': []
            }

        # Build context
        context_parts = []
        citations = []

        for chunk in relevant_chunks:
            context_parts.append(chunk['text'])
            citation = f"{chunk['metadata']['filename']} (Page {chunk['metadata']['page']})"
            citations.append(citation)

        context = "\n\n---\n\n".join(context_parts)
        unique_citations = list(dict.fromkeys(citations))  # Preserve order, remove duplicates

        # Generate answer with Gemini
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-1.5-flash')

        prompt = f"""You are a helpful document assistant. Answer the question based ONLY on the context below.

If the answer is not in the context, say "I cannot find this information in the uploaded documents."

CONTEXT:
{context}

QUESTION: {question}

ANSWER:"""

        response = model.generate_content(prompt)

        return {
            'answer': response.text,
            'citations': unique_citations
        }

# Initialize chatbot
print("="*60)
print("🤖 Ask My PDF - RAG Chatbot (Fixed Version)")
print("="*60)
chatbot = SimpleRAGChatbot()

print("\n📁 STEP 1: Upload your PDF files")
print("-"*40)

# Upload files
uploaded = files.upload()

# Save uploaded files to disk
saved_files = []
for filename in uploaded.keys():
    # Save with original name
    with open(filename, 'wb') as f:
        f.write(uploaded[filename])
    saved_files.append(filename)
    print(f"✓ Saved: {filename}")

print(f"\n✅ {len(saved_files)} file(s) saved successfully")

# ============================================
# CELL 4: Process Documents
# ============================================
print("\n🔧 STEP 2: Processing Documents")
print("-"*40)

if saved_files:
    num_chunks = chatbot.add_documents(saved_files)
    if num_chunks > 0:
        print(f"\n🎉 Ready to answer questions!")
    else:
        print("\n⚠️ Couldn't extract text. Make sure:")
        print("   1. PDFs contain selectable text (not scanned images)")
        print("   2. Files are not password protected")
        print("   3. Files are valid PDFs")
else:
    print("❌ No files uploaded. Please upload PDFs.")

print("\n" + "="*60)
print("💬 STEP 3: Ask Questions About Your Documents")
print("="*60)

# Get Gemini API key (free)
print("\n🔑 You need a free Gemini API key")
print("   Get it from: https://makersuite.google.com/app/apikey")
print("   (Free tier: 60 requests/minute)\n")

api_key = input("📝 Paste your API key here: ").strip()

if not api_key:
    print("\n❌ API key required. Please get one from the link above.")
    print("   Run this cell again after getting your key.")
elif num_chunks == 0:
    print("\n❌ No documents loaded. Please upload PDFs in Cell 3 first.")
else:
    print("\n✅ Ready! Type your questions below.")
    print("   Type 'quit', 'exit', or 'q' to stop\n")

    question_count = 0
    while True:
        question = input(f"\n❓ [{question_count + 1}] Your question: ")

        if question.lower() in ['quit', 'exit', 'q']:
            print(f"\n👋 Goodbye! You asked {question_count} questions.")
            break

        if not question.strip():
            print("   Please enter a question.")
            continue

        print("\n🔍 Searching through documents...")
        result = chatbot.ask(question, api_key)

        print("\n" + "="*60)
        print("📝 ANSWER:")
        print("="*60)
        print(result['answer'])

        if result['citations']:
            print("\n📚 SOURCES:")
            for citation in result['citations']:
                print(f"   • {citation}")
        print("="*60)

        question_count += 1

# Cell 4 Alternative - For Scanned PDFs
!apt-get install -y poppler-utils tesseract-ocr
!pip install -q pytesseract pdf2image

from pdf2image import convert_from_path
import pytesseract

def extract_text_from_scanned(file_path):
    images = convert_from_path(file_path)
    text = ""
    for img in images:
        text += pytesseract.image_to_string(img)
    return text